### ISSUE TITLE
Kernel panic!!!

### ISSUE THREAD

**Issue by burramsettyarvind** [KLGLUG/Xenomai#3]
code model kernel doesnt support PIC mode
![error2](https://user-images.githubusercontent.com/26138737/32687979-ed4f6f18-c695-11e7-8cea-c31c9bda1ef8.jpg)

**Comment by Abhilash02** [comment]
The issue is with your gcc installation, in gcc 6+ versions PIE( position independent executables) is enabled by default. So in order to compile you need to disable it. Even gcc 5 has the issue. This is a known bug for gcc.So the appropriate solution is to compile the kernel of version suitable to your gcc compiler.
